---
jenkins_credentials:    
  system:
    domainCredentials:
      - credentials:
           - basicSSHUserPrivateKey:
               scope: GLOBAL
               id: '{{ git_id }}'
               username: '{{ git_username }}'
               passphrase: '{{ git_passphrase|default("") }}'
               description: 'Key to authenticate towards git'
               privateKeySource:
                 directEntry:
                   privateKey: '{{ vault_git_ssh_key }}'