---
jenkins_credentials:    
  system:
    domainCredentials:
      - credentials:
           - basicSSHUserPrivateKey:
               scope: GLOBAL
               id: '{{ git_id }}'
               username: '{{ git_username }}'
               passphrase: '{{ git_passphrase|default("") }}'
               description: 'Key to authenticate towards git'
               privateKeySource:
                 directEntry:
                   privateKey: '{{ vault_git_ssh_key }}'
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: '574c297b-5d98-46d7-aaa0-4a34d4b9cc40'
              username: jenkins
              privateKeySource:
                directEntry:
                  privateKey: '{{ vault_jenkins_node_key }}'
          - string:
              scope: GLOBAL
              id: repo_key
              secret: '{{ vault_repo_key }}'
              description: API Key
          - usernamePassword:
              scope: GLOBAL
              id: 'IL2_JENKINS_SERVICE_ADMIN'
              username: svc_jenkins_portal
              password: '{{ vault_il2_jenkins_service_admin }}'
              description: 'Jenkins Service Account'